export const supabaseUrl = "https://gfaufxcpnjezuilhxpob.supabase.co";
export const supabaseAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmYXVmeGNwbmplenVpbGh4cG9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzOTE0MzksImV4cCI6MjA1MDk2NzQzOX0.jPj_LwQ9qxzxdg4erKkoFbZbCWzl-8jNrn67bnrAZG8";
